name: Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout template
        uses: actions/checkout@v4
        with:
          repository: arcanis/mael-docs
          ssh-key: '${{secrets.MAEL_DOCS_KEY}}'
          path: ./mael-docs

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Enable Corepack
        run: corepack enable

      - name: Build the website
        run: |
          yarn install
          cd mael-docs
          yarn install
          DOCS_DIR=$(realpath ../docs) yarn next build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./mael-docs/out

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
