name: Pages

on:
  workflow_dispatch:
  page_build:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout template
        uses: actions/checkout@v4
        with:
          ssh-key: '${{secrets.MAEL_DOCS_KEY}}'
          path: ./mael-docs

      - name: Build the website
        run: |
          cd mael-docs
          yarn
          DOCS_DIR=$(realpath ../docs) yarn next build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./mael-docs/out

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
